// 1. CONFIGURACIÓN GLOBAL
const CONTACTO_GLOBAL = {
    whatsapp: "34655296123", // Formato: Código país + número
    telefono: "934772012",
    email: "info@finquestivi3.com"
}

const DESCRIPCIONES_PUEBLOS = {
        "Miami Platja": "<strong>Miami Platja</strong> es una población de la Costa Dorada conocida por sus maravillosas playas y calas, algunas de las cuales están reconocidas con la distinción de bandera azul, por la limpieza de sus aguas e instalaciones, y los servicios que ofrecen. Además de estar pegada a Hospitalet de l’Infant, se encuentra también muy cerca de otros núcleos urbanos muy destacados: A menos de 15 km tenemos la población costera de Cambrils, y en un radio de 30 km se encuentran Salou, Tarragona y Reus, ciudad que cuenta con su propio aeropuerto. Algunos de los atractivos turísticos más icónicos con los que cuenta Miami, además de sus playas, son su variada oferta en restauración, su disponibilidad de deportes náuticos, sus paisajes habilitados para el senderismo, su centro hípico, el campo de golf Bonmont, e incluso se encuentra a tan solo 20 minutos en coche del famoso parque de atracciones Port Aventura.",
        "Sant Joan Despí": "<strong>Sant Joan Despí</strong>, reconocida por albergar los estudios de TV3, es una población muy bien comunicada, con entrada y salida a los accesos a vías rápidas con conexión a cualquier punto del Baix Llobregat, Barcelona y Vallés. Justo al lado dispone de acceso a la autovía B-23 y a la carretera C-245, así como los municipios de Cornellá de Llobregat, Esplugues de Llobregat y Sant Just Desvern.",
        "Hospitalet de l'Infant": "<strong>Hospitalet de l'Infant</strong> es una población de la Costa Dorada conocida por sus maravillosas playas, algunas de las cuales están reconocidas con la distinción de bandera azul, por la limpieza de sus aguas e instalaciones, y los servicios que ofrecen. Además de estar pegada a Miami Platja, se encuentra también muy cerca de otros núcleos urbanos muy destacados: A menos de 15 km tenemos la población costera de Cambrils, y en un radio de 30 km se encuentran Salou, Tarragona y Reus, ciudad que cuenta con su propio aeropuerto. Algunos de los atractivos turísticos más icónicos con los que cuenta Hospitalet de l'Infant, además de sus playas, son su transitado puerto náutico, su variada oferta en restauración e incluso ocio nocturno, su disponibilidad de deportes náuticos, sus calles pensadas para ir paseando, e incluso se encuentra a tan solo 20 minutos en coche del famoso parque de atracciones Port Aventura.",
        "Cambrils": "<strong>Cambrils</strong> es un gran destino para vivir todo el año. Es una población de la costa dorada, con una forma de vida muy modernizada y con todas las comodidades que se pueden pedir: gran variedad en cuanto a formación académica, una amplia oferta en hostelería, un largo paseo marítimo muy transcurrido y muy característico del municipio, etc. Cambrils a su vez se encuentra muy bien conectado con el resto de poblaciones y ciudades de Tarragona, ya que cuenta con estación de tren, y con múltiples líneas de bus que conectan a Cambrils con sus localidades vecinas de Salou, Reus, Tarragona, Vila-fortuny, Miami Platja, Vila-Seca, La Pineda, etc.",
        "Tarragona": "<strong>Tarragona</strong> es la capital de su provincia y por lo tanto es una ciudad con mucha vida. Es una preciosa ciudad costera con mucha historia y un lugar en el que siempre hay movimiento.",
        "Tivissa": "<strong>Tivissa</strong> es una carismática población de montaña conocida por su entorno natural y su patrimonio histórico medieval. Situada a los pies de su propia sierra, es un referente para el senderismo y la escalada, destacando también por el yacimiento ibérico del Castellet de Banyoles. Se encuentra a solo 20 minutos de las playas de Hospitalet de l'Infant y Miami Platja, ofreciendo un refugio de tranquilidad muy cerca de los principales núcleos de la Costa Dorada.",
        "La Seu d'Urgell": "<strong>La Seu d'Urgell</strong> es una histórica ciudad del Pirineo conocida por ser la capital de la comarca del Alt Urgell y la sede del Obispado de Urgell. Destaca por su impresionante catedral románica de Santa Maria y su entorno natural privilegiado, ideal para los deportes de aventura y el piragüismo en su canal olímpico. Gracias a su ubicación estratégica, actúa como principal puerta de entrada a Andorra, situada a tan solo 10 km, y ofrece una excelente conexión con el Parque Natural del Cadí-Moixeró.",
        "Cornellà de Llobregat": "<strong>Cornellà de Llobregat</strong> es una ciudad estratégica y dinámicamente conectada, situada en el corazón de la comarca del Baix Llobregat. Destaca por su excelente red de transporte público y accesos viarios, que permiten llegar al centro de Barcelona y al aeropuerto en pocos minutos. Es una población con gran actividad comercial y deportiva, conocida por albergar el estadio del RCDE Espanyol y el recinto ferial de la Fira de Cornellà, además de ofrecer amplias zonas verdes como el Parc de Can Mercader."
    };
    
const DISCLAIMER_LEGAL = "En cumplimiento de la ley 3/2917 del 13 de febrero del 2018 del código civil de Catalunya el cual se aprueba el reglamento de información al consumidor en la compraventa y arrendamiento de viviendas de Catalunya, se informa al cliente que los gastos notariales, registrales e impuestos que se le apliquen (ITP, IVA o AJD) y otros gastos inherentes de la compraventa no están incluidos en el precio.";


// 2. BASE DE DATOS
const inmuebles = [
    { 
        id: "CZ285",
        titulo: "Adosado en el centro de Miami Platja", 
        precio: "218.000 €", 
        poblacion: "Miami Platja", 
        tipo: "Casa", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/L4gNRSQM/cz285_01.jpg",
            "https://i.postimg.cc/7PJmD4tk/cz285_02.jpg",
            "https://i.postimg.cc/44HBZG2s/cz285_03.jpg",
            "https://i.postimg.cc/nc8ThWgg/cz285_04.jpg",
            "https://i.postimg.cc/L4gNRSQH/cz285_05.jpg",
            "https://i.postimg.cc/9F31QksX/cz285_06.jpg",
            "https://i.postimg.cc/Yqc8CPTj/cz285_07.jpg",
            "https://i.postimg.cc/jdVvS1BS/cz285_08.jpg",
            "https://i.postimg.cc/9F31QksM/cz285_09.jpg",
            "https://i.postimg.cc/DyV5wNRW/cz285_10.jpg",
            "https://i.postimg.cc/fT45RP10/cz285_11.jpg",
            "https://i.postimg.cc/284GbwfV/cz285_12.jpg",
            "https://i.postimg.cc/MKy5MD8d/cz285_13.jpg",
            "https://i.postimg.cc/Dyq6JgK5/cz285_14.jpg",
            "https://i.postimg.cc/7Yg9GVy0/cz285_15.jpg",
            "https://i.postimg.cc/ncv2jktK/cz285_16.jpg",
            "https://i.postimg.cc/zXn7bj1t/cz285_17.jpg",
            "https://i.postimg.cc/8zNHh61K/cz285_18.jpg",
            "https://i.postimg.cc/g2mDvZYs/cz285_19.jpg",
            "https://i.postimg.cc/CxSNjqFX/cz285_20.jpg",
        ],
        metros: 80, 
        parcela: 140, 
        habitaciones: 2, 
        baños: 1, 
        garaje: "Sí",
        descripcion: "Finques TIVI3 presenta este adosado en el centro de Miami Platja. Su estructura distribuida en una planta baja única de 80 metros cuadrados nos brinda un inmueble con salón-comedor, dos habitaciones con espacio suficiente para colocar una cama doble, una acogedora cocina con todo lo necesario, y un baño con plato de ducha y bidé. La vivienda se ve completada con una amplia terraza que se puede destinar a múltiples usos ya que cabe una gran mesa y barbacoa, e incluso se ha destinado en el pasado para colocar una piscina. También incluye por supuesto un garaje cubierto privado y acceso a la vivienda por dos portones así que se puede perfectamente aparcar un segundo vehículo que no esté a cubierto."
    },
    { 
        id: "CZ382",
        titulo: "Casa con gran terreno en Vanessa Park", 
        precio: "420.000 €", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Casa", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/2ST9XwyT/cz382-01.jpg",
            "https://i.postimg.cc/NjbCP4Fp/cz382-02.jpg",
            "https://i.postimg.cc/9Q1gNp0B/cz382-03.png",
            "https://i.postimg.cc/RZGpbRhc/cz382-04.jpg",
            "https://i.postimg.cc/GmzgSQtf/cz382-05.jpg",
            "https://i.postimg.cc/13M7YHX2/cz382-06.jpg",
            "https://i.postimg.cc/rpmZ6rRg/cz382-07.jpg",
            "https://i.postimg.cc/s2XHFhGn/cz382-08.jpg",
            "https://i.postimg.cc/yNdpqZ3p/cz382-09.jpg",
            "https://i.postimg.cc/vmB2RVxN/cz382-10.jpg",
            "https://i.postimg.cc/VN6ZyC03/cz382-11.jpg",
            "https://i.postimg.cc/yNdpqZSC/cz382-12.jpg",
            "https://i.postimg.cc/hGjZFd7q/cz382-13.jpg",
            "https://i.postimg.cc/Bv67WK1q/cz382-14.jpg",
            "https://i.postimg.cc/Bv67WK1n/cz382-15.jpg",
            "https://i.postimg.cc/43d2C9hd/cz382-16.jpg",
            "https://i.postimg.cc/rpmZ6rtp/cz382-17.jpg",
            "https://i.postimg.cc/vmNqGZWy/cz382-18.jpg",
            "https://i.postimg.cc/rpPnqwSc/cz382-19.jpg",
            "https://i.postimg.cc/MGFPzpyW/cz382-20.jpg",
            "https://i.postimg.cc/9fn8cQGc/cz382-21.jpg",
            "https://i.postimg.cc/MGFPzpyK/cz382-22.jpg"
        ],
        metros: 2770, 
        parcela: 16460, 
        habitaciones: 1, 
        baños: 2, 
        descripcion: "En la tranquila y plácida urbanización Vanessa Park, a medio camino entre la localidad de Hospitalet de l’Infant y la de Vandellòs, encontramos este exclusivo recinto, único en la zona, con una inmensa parcela que da lugar a un magnífico chalet independiente de 112 metros cuadrados con una sala de estar, una habitación, cocina, dos baños y hasta un pequeño taller. La casa cuenta con una súper terraza cubierta por un gran porche construido recientemente con madera maciza de unos 100 metros cuadrados, una gran piscina, y vastas zonas ajardinadas. En total, dentro de la parcela de unos sonoros 16.460 metros cuadrados, tenemos 2.770 metros cuadrados edificados entre todas las estancias nombradas y 4 pistas de tenis profesional. Con la posibilidad de cualquier ampliación y reforma que se ajuste a sus necesidades o anhelos gracias al gran terreno con el que cuenta esta propiedad. El recinto ha sido durante años un club de tenis de referencia en la zona, cuyas instalaciones cuentan con 4 pistas de tenis, piscina, bar con terraza, parking, etc. Esto puede seguir siendo así si usted lo desea, seguir el negocio o destinar el recinto como tu casa de ensueño."
    },
    { 
        id: "CZ517",
        titulo: "Local en el Puerto de Hospitalet", 
        precio: "72.000 €", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/bJMQBmK6/cz517-01.jpg",
            "https://i.postimg.cc/Y9V1sdJn/cz517-02.jpg",
            "https://i.postimg.cc/cHjQbFVV/cz517-03.jpg",
            "https://i.postimg.cc/NMV1zdWV/cz517-04.jpg",
            "https://i.postimg.cc/NMV1zd3c/cz517-05.jpg",
            "https://i.postimg.cc/PxcmRSgh/cz517-06.jpg",
            "https://i.postimg.cc/Y9V1sd5r/cz517-07.jpg",
            "https://i.postimg.cc/cCnQyQSP/cz517-08.jpg",
            "https://i.postimg.cc/sxhpdpzR/cz517-09.jpg",
            "https://i.postimg.cc/J0kbVb88/cz517-10.jpg",
            "https://i.postimg.cc/C5qjTj0Y/cz517-11.jpg",
            "https://i.postimg.cc/x8zKDKQ9/cz517-12.jpg",
            "https://i.postimg.cc/MHQy2ywX/cz517-13.jpg",
            "https://i.postimg.cc/907G5G2r/cz517-14.jpg",
            "https://i.postimg.cc/d3y8P8Fk/cz517-15.jpg",
            "https://i.postimg.cc/Y0W1K17m/cz517-16.jpg",
            "https://i.postimg.cc/RhHc5cmc/cz517-17.jpg",
            "https://i.postimg.cc/FFdbLQLD/cz517-18.jpg",
            "https://i.postimg.cc/dQkRyKyf/cz517-19.jpg",
            "https://i.postimg.cc/ZYBPdhdX/cz517-20.jpg"
        ],
        metros: 60, 
        baños: 2, 
        descripcion: "En el emblemático puerto de Hospitalet de l'Infant tenemos este local el cual actualmente es un restaurante en funcionamiento con su clientela habitual, en la zona más concurrida de esta población y alrededores. Aprovecha la tracción de gente que tiene este lugar para ubicar y darle vida a tu proyecto. Se trata de un local de 60 metros cuadrados con 30 más de terraza, que está listo para iniciar las obras de remodelación que encuentres adecuadas. Muy bien ubicado en el paseo marítimo, el cual ha dado y da vida a una gran variedad de puntos de interés tales como restaurantes, cafeterías, bares, tiendas, oficinas, etc."
    },
    { 
        id: "3013",
        titulo: "Plaza de parking en Sant Joan Despí", 
        precio: "17.500€", 
        poblacion: "Sant Joan Despí", 
        tipo: "Parking", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/DZTwvFMX/3013-01.jpg",
            "https://i.postimg.cc/1tQ3mPjw/3013-02.jpg",
            "https://i.postimg.cc/26DSkmKx/3013-03.jpg",
            "https://i.postimg.cc/0QsykxBf/3013-04.jpg"
        ],
        metros: 13,  
        descripcion: "Cómoda plaza de parking de un garaje cubierto ubicado en Sant Joan Despí, concretamente en la calle Sant Martí de l´Erm."
    },
    { 
        id: "CZ180",
        titulo: "Apartamento en el centro de Miami Platja", 
        precio: "130.000€", 
        poblacion: "Miami Platja", 
        tipo: "Piso", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/d10F517f/cz180-01.jpg",
            "https://i.postimg.cc/HxLm6xJf/cz180-02.jpg",
            "https://i.postimg.cc/TwPxtwyB/cz180-03.jpg",
            "https://i.postimg.cc/DZzhxZWD/cz180-04.jpg",
            "https://i.postimg.cc/tTgbBTZ9/cz180-05.jpg",
            "https://i.postimg.cc/KzYb0zkx/cz180-06.jpg",
            "https://i.postimg.cc/sX2zTXQg/cz180-07.jpg",
            "https://i.postimg.cc/V6NwK6rL/cz180-08.jpg",
            "https://i.postimg.cc/ydNKLdgW/cz180-09.jpg",
            "https://i.postimg.cc/V6NwK6rr/cz180-10.jpg",
            "https://i.postimg.cc/C1K0c1BR/cz180-11.jpg",
            "https://i.postimg.cc/FRKvTRdf/cz180-12.jpg",
            "https://i.postimg.cc/LX0pwpLs/cz180-13.jpg"
        ],
        metros: 85, 
        habitaciones: 1, 
        baños: 1, 
        descripcion: "Finques TIVI3 presenta este moderno apartamento situado en la avenida principal de la población de Miami Playa. Ubicado encima de un local comercial que se encuentra también a la venta por 90.000€, perfecto para realizar una compra conjunta y llevar a cabo un proyecto de vida idóneo. El apartamento cuenta con instalaciones modernas, tales como sistema de aerotermia y aire acondicionado, y acabados muy cuidados a lo largo de sus 85 metros cuadrados, distribuidos entre un amplio salón con una gran cocina integrada en la que no tendrás problemas de espacio, y con una barra americana que separa la cocina del salón. Al fondo podemos avistar el pasillo, el cual lleva a la suite del hogar, sin olvidarnos por supuesto del baño completo con plato de ducha que encontramos de camino. Retomando con la suite, ésta es espaciosa como se puede apreciar, con lugar para una cama king-size y un armario grande muy útil. Y no hay que olvidarse de que la suite te brinda acceso a esa maravillosa terraza destinable a múltiples usos, orientada hacia la avenida Barcelona, la cual alberga mucha vida y movimiento."
    },
    { 
        id: "CZ274",
        titulo: "Adosado en 2ª línea de mar", 
        precio: "450.000€", 
        poblacion: "Miami Platja", 
        tipo: "Casa", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/SR2hpvGm/cz274-01.jpg",
            "https://i.postimg.cc/sxQrRNJj/cz274-02.jpg",
            "https://i.postimg.cc/HncgChtW/cz274-03.jpg",
            "https://i.postimg.cc/sxkRf4Tt/cz274-04.jpg",
            "https://i.postimg.cc/QC2rNJ6Z/cz274-05.jpg",
            "https://i.postimg.cc/cCpN1BDW/cz274-06.jpg",
            "https://i.postimg.cc/MHC8Zms8/cz274-07.jpg",
            "https://i.postimg.cc/5yhM9SPb/cz274-08.jpg",
            "https://i.postimg.cc/mkvGZydZ/cz274-09.jpg",
            "https://i.postimg.cc/br7jY96w/cz274-10.jpg",
            "https://i.postimg.cc/SRBpQfZR/cz274-11.jpg",
            "https://i.postimg.cc/Y05w2zXj/cz274-12.jpg",
            "https://i.postimg.cc/HnqCW9SJ/cz274-13.jpg",
            "https://i.postimg.cc/MHC8ZmsM/cz274-14.jpg",
            "https://i.postimg.cc/yxMz6yf9/cz274-15.jpg",
            "https://i.postimg.cc/PJgkfQ61/cz274-16.jpg",
            "https://i.postimg.cc/wxZzk99w/cz274-17.jpg",
            "https://i.postimg.cc/fWpsvMMH/cz274-18.jpg",
            "https://i.postimg.cc/Y2Z7xttP/cz274-19.jpg",
            "https://i.postimg.cc/Kcwb5mms/cz274-20.jpg"
        ],
        metros: 145, 
        habitaciones: 4, 
        baños: 3, 
        descripcion: "Chalet adosado a segunda línea de mar en Miami Platja. Un amplio patio es la antesala de esta vivienda, donde podrás encontrar una zona de césped artificial, barbacoa, etc. Un porche, equipado con una gran mesa, es el que da la entrada al inmueble de dos plantas. Dentro nos encontramos con un gran salón, una cocina y un baño. En la segunda planta tenemos las habitaciones, los baños, y una terraza con vistas a la playa."
    },
    { 
        id: "CZ276",
        titulo: "Adosado de 2 plantas en Masos", 
        precio: "235.000€", 
        poblacion: "", 
        tipo: "Miami Platja", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/VNfPN6Fq/cz276-01.jpg",
            "https://i.postimg.cc/nLFfLz1q/cz276-02.jpg",
            "https://i.postimg.cc/PqXnqxMY/cz276-03.jpg",
            "https://i.postimg.cc/43fR3d1Q/cz276-04.jpg",
            "https://i.postimg.cc/MG6JGTYY/cz276-05.jpg",
            "https://i.postimg.cc/9fmHfMB1/cz276-06.jpg",
            "https://i.postimg.cc/0Nk1NQCf/cz276-07.jpg",
            "https://i.postimg.cc/tgqGgTzr/cz276-08.jpg",
            "https://i.postimg.cc/BvSfv6CY/cz276-09.jpg",
            "https://i.postimg.cc/W4Nc437f/cz276-10.jpg",
            "https://i.postimg.cc/vmYwmBv2/cz276-11.jpg",
            "https://i.postimg.cc/nLFfLz1P/cz276-12.jpg",
            "https://i.postimg.cc/d05PZYWR/cz276-13.jpg",
            "https://i.postimg.cc/KY0S329r/cz276-14.jpg"
        ],
        metros: 95, 
        parcela: 150, 
        habitaciones: 3, 
        baños: 2, 
        descripcion: "Conoce este magnífico adosado de dos plantas que te enamorará, en la urbanización de Masos d'en Blader, a las afueras de Miami Platja. Recorre su amplio salón-comedor con aire acondicionado, su cocina completamente equipada, sus dos espaciosas habitaciones dobles con armarios empotrados, una habitación individual, y sus dos baños, uno de ellos completo con bañera y el otro un aseo. No olvidemos su gran terraza solárium que se ubica en la parte alta de la casa, ni tampoco el acceso a una cómoda piscina rodeada de zonas ajardinadas (accesible para las 6 casas de la comunidad). El adosado cuenta con garaje y trasero exterior."
    },
    { 
        id: "CZ392",
        titulo: "Casa en Hospitalet de l'Infant", 
        precio: "320.000€", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Casa", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/s2gfNKbf/cz392-01.jpg",
            "https://i.postimg.cc/0Ny5BZhN/cz392-02.jpg",
            "https://i.postimg.cc/TP324QBw/cz392-03.jpg",
            "https://i.postimg.cc/d0VQxngt/cz392-04.jpg",
            "https://i.postimg.cc/N0jGzbZF/cz392-05.jpg",
            "https://i.postimg.cc/YSD2KYww/cz392-06.jpg",
            "https://i.postimg.cc/s2Hfd7Ry/cz392-07.jpg",
            "https://i.postimg.cc/9fgX5Zj2/cz392-08.jpg",
            "https://i.postimg.cc/JhY7VZWh/cz392-09.jpg",
            "https://i.postimg.cc/KYpcSBy1/cz392-10.jpg",
            "https://i.postimg.cc/YSD2KYwm/cz392-11.jpg",
            "https://i.postimg.cc/8CXkQMV6/cz392-12.jpg",
            "https://i.postimg.cc/cJk1ywN7/cz392-13.jpg",
            "https://i.postimg.cc/R0pC5KzQ/cz392-14.jpg",
            "https://i.postimg.cc/259jRhfx/cz392-15.jpg",
            "https://i.postimg.cc/637W9q94/cz392-16.jpg",
            "https://i.postimg.cc/76CHxhxS/cz392-17.jpg",
            "https://i.postimg.cc/xCkf080G/cz392-18.jpg",
            "https://i.postimg.cc/wvtq6M6Q/cz392-19.jpg",
            "https://i.postimg.cc/DZWv202Y/cz392-20.jpg"
        ],
        metros: 187, 
        habitaciones: 3, 
        baños: 0, 
        descripcion: "Finques TIVI3 presenta este chalet de 187m2 con un jardín de 190m2. Consta de salón-comedor con chimenea y cocina en una estancia grande y amplia, 5 habitaciones (3 de ellas dobles, de las cuales una se encuentra en la buhardilla y tiene su terraza propia), 2 baños completos, un amplio jardín, una suma total de 5 terrazas alrededor de la casa, aire acondicionado en 4 estancias, radiadores alimentados por una caldera eléctrica central y garaje privado en la vivienda."
    },
    { 
        id: "CZ415",
        titulo: "Solar residencial en Miami Platja", 
        precio: "120.000€", 
        poblacion: "Miami Platja", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/0jGDfPz4/cz415-01.jpg",
            "https://i.postimg.cc/NF8m4BKP/cz415-02.jpg",
            "https://i.postimg.cc/Vv9nRmJG/cz415-03.jpg",
            "https://i.postimg.cc/8cdMHN7s/cz415-04.jpg"
        ],
        parcela: 514, 
        descripcion: "El terreno está situado en Miami Platja, un núcleo de población situado en la costa donde se puede disfrutar de sus largas playas y clima cálido. Es un pueblo muy bien situado, conocido como un perfecto lugar para pasar las vacaciones en familia con tranquilidad, y está equipado con todo tipo de comodidades tales como restaurantes, tiendas, supermercados, etc."
    },
    { 
        id: "CZ417",
        titulo: "Solar residencial en Hospitalet de l'Infant", 
        precio: "105.000€", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/hG7Jscw1/cz417-01.jpg",
            "https://i.postimg.cc/wBst2gPV/cz417-02.jpg",
            "https://i.postimg.cc/cJ8Kh0j8/cz417-03.jpg",
            "https://i.postimg.cc/1zNgBsTq/cz417-04.jpg",
            "https://i.postimg.cc/XvyZL4hx/cz417-05.jpg",
            "https://i.postimg.cc/9M5DNs5P/cz417-06.jpg",
            "https://i.postimg.cc/nzbXwNb3/cz417-07.jpg",
            "https://i.postimg.cc/1th8YbhK/cz417-08.jpg"
        ],
        parcela: 850, 
        descripcion: "El terreno está situado en Hospitalet de l´Infant. Siendo un núcleo de población situado en la costa se puede disfrutar de sus largas playas y clima cálido. Se encuentra también en un punto donde diferentes vías se cruzan para comodidad de sus habitantes a la hora de viajar y visitar las poblaciones lindantes. Pueblo perfecto para pasar las vacaciones en familia y con tranquilidad."
    },
{
        id: "CZ418",
        titulo: "Solar residencial en Miami Platja", 
        precio: "195.000€", 
        poblacion: "Miami Platja", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/6qzTq32X/cz418-01.jpg",
            "https://i.postimg.cc/rsgzsm06/cz418-02.jpg",
            "https://i.postimg.cc/Znj0nR9X/cz418-03.jpg",
            "https://i.postimg.cc/y6TDvffS/cz418-04.jpg",
            "https://i.postimg.cc/RCTWXPPW/cz418-05.jpg",
            "https://i.postimg.cc/L4VJNyyV/cz418-06.jpg",
            "https://i.postimg.cc/XNgrQ22c/cz418-07.jpg",
            "https://i.postimg.cc/bYRZ366K/cz418-08.jpg"
        ],
        parcela: 842, 
        descripcion: "Finques TIVI3 presenta este solar urbano de 842 metros cuadrados en el centro de Miami Platja."
    },
    { 
        id: "CZ425",
        titulo: "Solar residencial en Hospitalet de l'Infant", 
        precio: "675.000€", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/ncRCtXfY/cz425-01.jpg",
            "https://i.postimg.cc/gkSnPxbD/cz425-02.jpg",
            "https://i.postimg.cc/ncRCtXf0/cz425-03.jpg",
            "https://i.postimg.cc/kX1Bd2Pw/cz425-04.jpg",
            "https://i.postimg.cc/g2xrcGG8/cz425-05.jpg",
            "https://i.postimg.cc/bwZdYqqH/cz425-06.jpg"
        ],
        parcela: 1350, 
        descripcion: "Gran terreno en la Calle Pontasgo de Hospitalet de l'Infant, con vistas a la playa, y una superfície gráfica de 1.350 metros cuadrados."
    },
    { 
        id: "CZ428",
        titulo: "Solar industrial en Hospitalet de l'Infant", 
        precio: "128.000€", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/HnWsqgSX/cz428-01.jpg",
            "https://i.postimg.cc/1XR5kQW6/cz428-02.jpg"
        ],
        parcela: 751,  
        descripcion: "El terreno está situado en el polígono industrial d´Hospitalet de l´Infant. Su núcleo de población está situado en la costa, donde se puede disfrutar de sus largas playas y clima cálido. Se encuentra también en un punto donde diferentes vías se cruzan para comodidad de sus habitantes a la hora de viajar y visitar las poblaciones lindantes. Pueblo perfecto para pasar las vacaciones en familia y con tranquilidad."
    },
    { 
        id: "CZ429",
        titulo: "Solar residencial en Hospitalet de l'Infant", 
        precio: "115.000€", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/VNysYMGC/cz429-01.jpg",
            "https://i.postimg.cc/25pjzvcL/cz429-02.jpg",
            "https://i.postimg.cc/PqGftZ38/cz429-03.jpg",
            "https://i.postimg.cc/8C8k1WKv/cz429-04.jpg",
            "https://i.postimg.cc/xdrj0HxG/cz429-05.jpg",
            "https://i.postimg.cc/Lsz9hXwJ/cz429-06.jpg",
            "https://i.postimg.cc/cJQx6H2K/cz429-07.jpg"
        ],
        parcela: 820,  
        descripcion: "El terreno está situado a las afueras de Hospitalet de l´Infant, un núcleo de población situado en la costa donde se puede disfrutar de sus largas playas y clima cálido. La zona donde se encuentra el terreno está muy bien comunicada, cercana tanto a la población como a áreas de servicio, supermercados, el polígono industrial, y ubicado de forma muy cómoda junto a una red de carreteras que te comunicará directamente con la A-7 (autovía del mediterráneo) como con la AP-7 (autopista del mediterráneo)."
    },
    { 
        id: "CZ430",
        titulo: "Solar industrial en Miami Platja", 
        precio: "225.000€", 
        poblacion: "Miami Platja", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/8ky17xKX/cz430-01.jpg",
            "https://i.postimg.cc/05t8zhWf/cz430-02.jpg",
            "https://i.postimg.cc/nrwZNQ99/cz430-03.jpg",
            "https://i.postimg.cc/448JYjLF/cz430-04.jpg",
            "https://i.postimg.cc/T2kRKBN2/cz430-05.jpg",
            "https://i.postimg.cc/VLdzn42Q/cz430-06.jpg",
            "https://i.postimg.cc/SNJmCVHm/cz430-07.jpg",
            "https://i.postimg.cc/Fs7h3GwN/cz430-08.jpg",
            "https://i.postimg.cc/28VChTg8/cz430-09.jpg",
            "https://i.postimg.cc/J4GRZKSz/cz430-10.jpg",
            "https://i.postimg.cc/m2tTCVKr/cz430-11.jpg",
            "https://i.postimg.cc/hPfKTMNh/cz430-12.jpg",
            "https://i.postimg.cc/ZKCJpjXC/cz430-13.jpg",
            "https://i.postimg.cc/SNJmCVHn/cz430-14.jpg",
            "https://i.postimg.cc/WbhsgSxq/cz430-15.jpg"
        ],
        parcela: 1980,  
        descripcion: "Tres parcelas contiguas de unos impresionantes 1.980 metros cuadrados, de 45 metros de ancho y 44 metros de largo, ubicadas en Les Tàpies, a las afueras de Hospitalet de l'Infant, muy cercano a la estación de servicio Alas. El terreno edificable se queda en 1.465 metros cuadrados, y es perfecto para albergar varias naves o cualquier otro cometido que se tenga en mente."
    },
    { 
        id: "CZ432",
        titulo: "Solar residencial en Cambrils", 
        precio: "150.000€", 
        poblacion: "Cambrils", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/cJNZqWCY/cz432-01.jpg",
            "https://i.postimg.cc/R0z9rmhH/cz432-02.jpg",
            "https://i.postimg.cc/pdtxNvrj/cz432-03.jpg",
            "https://i.postimg.cc/YSwkc70Y/cz432-04.jpg",
            "https://i.postimg.cc/N0wYhtF4/cz432-05.jpg",
            "https://i.postimg.cc/R0z9rmhd/cz432-06.jpg",
            "https://i.postimg.cc/7LyDv4hM/cz432-07.jpg"
        ],
        parcela: 503,  
        descripcion: "El solar está situado en Cambrils, un núcleo de población situado en la costa donde se puede disfrutar de sus largas playas y clima cálido. Es un pueblo muy bien situado, conocido como un perfecto lugar para pasar las vacaciones en familia con tranquilidad, y está equipado con todo tipo de comodidades tales como restaurantes, tiendas, supermercados, etc. Cuenta con un almacén de 24 metros cuadrados."
    },
    { 
        id: "CZ437",
        titulo: "Solar urbano en Miami Platja", 
        precio: "125.000€", 
        poblacion: "Miami Platja", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/C5dpCLPH/cz437-01.jpg",
            "https://i.postimg.cc/W35PJJnf/cz437-02.jpg",
            "https://i.postimg.cc/PxSk8843/cz437-03.jpg",
            "https://i.postimg.cc/Ssgpzzr1/cz437-04.jpg",
            "https://i.postimg.cc/7hbr1YsX/cz437-05.jpg",
            "https://i.postimg.cc/hvhR8PyY/cz437-06.jpg",
            "https://i.postimg.cc/D0m3QyjM/cz437-07.jpg"
        ],
        parcela: 555,  
        descripcion: "Finques TIVI3 presenta este terreno urbano de 555 metros cuadrados en el centro de Miami Platja, núcleo costero situado a unos de 30 kilómetros al sur de Tarragona. Las dos carreteras principales son la A-7 (Autovía del Mediterráneo), y la AP-7/E15 (Autopista del Mediterráneo), perfectas para moverse por los diferentes municipios cercanos. Miami es perfecto para disfrutar tanto de la montaña como de la costa."
    },
    { 
        id: "CZ438",
        titulo: "Parcela agrícola en Hospitalet de l'Infant", 
        precio: "145.000€", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/sDkCSzpK/cz438-01.jpg"
        ],
        parcela: 42115,  
        descripcion: "A las afueras de Hospitalet de l'Infant, colindando con la urbanización Vanessa Park y con la autopista AP-7, tenemos esta parcela rústica de 42.115 metros cuadrados que puede ser destinada a finalidades agrícolas y de cultivo."
    },
    { 
        id: "CZ500",
        titulo: "Local en el centro de Hospitalet de l'Infant", 
        precio: "141.000€", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/V6Lx1k8P/cz500-01.jpg",
            "https://i.postimg.cc/XJ7R3Yb0/cz500-02.jpg",
            "https://i.postimg.cc/0NCTLJLy/cz500-03.jpg",
            "https://i.postimg.cc/9fB6vqvf/cz500-04.jpg",
            "https://i.postimg.cc/gJkCd2Wn/cz500-05.jpg",
            "https://i.postimg.cc/fLTGZRNk/cz500-06.jpg",
            "https://i.postimg.cc/HxsqHkgr/cz500-07.jpg",
            "https://i.postimg.cc/NMf3YjcX/cz500-08.jpg",
            "https://i.postimg.cc/1t5kP3QD/cz500-09.jpg",
            "https://i.postimg.cc/V6Lx1k89/cz500-10.jpg",
            "https://i.postimg.cc/76spLrHC/cz500-11.jpg",
            "https://i.postimg.cc/507ZtW4L/cz500-12.jpg",
            "https://i.postimg.cc/G27ZpnLY/cz500-13.jpg",
            "https://i.postimg.cc/63jDQxWr/cz500-14.jpg"
        ],
        metros: 100, 
        baños: 1, 
        descripcion: "Consta de dos entradas una por Carrer Major y otra por Carrer Basses. Barra, altillo, cocina, sala principal, 2 lavabos y trastero. Con mobiliario mínimo.  En el principal núcleo urbano del municipio de Vandellós y Hospitalet de l'Infant, situado a la costa, a la derecha de la desembocadura del río de Llastre, que se le hace también de límite con el término de Mont-roig del Camp y el núcleo urbano de Miami Playa. *Inmueble disponible para proyecto, mas precisa de una reforma."
    },
    { 
        id: "CZ505",
        titulo: "Local + Vivienda en la Avenida Principal de Miami Platja", 
        precio: "175.000€", 
        poblacion: "Miami Platja", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/sxbqpPZB/cz505-01.jpg",
            "https://i.postimg.cc/8cx9hdrh/cz505-02.jpg",
            "https://i.postimg.cc/x8BhKGbv/cz505-03.jpg",
            "https://i.postimg.cc/pr34DQn5/cz505-04.jpg",
            "https://i.postimg.cc/PJ09mb82/cz505-05.jpg",
            "https://i.postimg.cc/9Xk652gs/cz505-06.jpg",
            "https://i.postimg.cc/CM23T06V/cz505-07.jpg",
            "https://i.postimg.cc/440DkGFZ/cz505-08.jpg",
            "https://i.postimg.cc/SQPBF4t4/cz505-09.jpg",
            "https://i.postimg.cc/ryHBXTYD/cz505-10.jpg",
            "https://i.postimg.cc/T2szMxHb/cz505-11.jpg",
            "https://i.postimg.cc/MZLC2wrQ/cz505-12.jpg",
            "https://i.postimg.cc/Pf7gsHF8/cz505-13.jpg",
            "https://i.postimg.cc/bN2Kq5Ks/cz505-14.jpg",
            "https://i.postimg.cc/jdJGR1GD/cz505-15.jpg",
            "https://i.postimg.cc/15NLydLg/cz505-16.jpg"
        ],
        metros: 202, 
        baños: 1, 
        descripcion: "Inmueble de dos plantas. La planta de abajo, un local que ha sido utilizado como bar, pero el cual puede ser destinado a cualquier tipo de actividad. La planta de arriba, un piso a rehabilitar con entrada independiente. Situado en la principal avenida de Miami Platja, la Avenida Barcelona."
    },
    { 
        id: "CZ507",
        titulo: "Nave industrial + Solar en Hospitalet de l'Infant", 
        precio: "578.000€", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Nave", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/W3HHvm88/cz507-01.jpg",
            "https://i.postimg.cc/KzHH27fN/cz507-02.jpg",
            "https://i.postimg.cc/G255CPK7/cz507-03.jpg",
            "https://i.postimg.cc/50RRV5gm/cz507-04.jpg",
            "https://i.postimg.cc/j5FFb6c9/cz507-05.jpg",
            "https://i.postimg.cc/Qtyy3gmw/cz507-06.jpg",
            "https://i.postimg.cc/MTFFS05h/cz507-07.jpg",
            "https://i.postimg.cc/0QBBsGZR/cz507-08.jpg",
            "https://i.postimg.cc/4yHFNK2M/cz507-09.jpg",
            "https://i.postimg.cc/V6VV894m/cz507-10.jpg",
            "https://i.postimg.cc/BbPwQ87d/cz507-11.jpg",
            "https://i.postimg.cc/Kj3svKsX/cz507-12.jpg",
            "https://i.postimg.cc/yx3rYJr4/cz507-13.jpg",
            "https://i.postimg.cc/d3ZSt7Sw/cz507-14.jpg",
            "https://i.postimg.cc/6q415713/cz507-15.jpg",
            "https://i.postimg.cc/5yQkNHk4/cz507-16.jpg",
            "https://i.postimg.cc/2yLX8qXq/cz507-17.jpg",
            "https://i.postimg.cc/j2nkdWkJ/cz507-18.jpg",
            "https://i.postimg.cc/cCt54K53/cz507-19.jpg",
            "https://i.postimg.cc/gjLBkwB8/cz507-20.jpg"
        ],
        metros: 610, 
        parcela: 1360,  
        descripcion: "Nave industrial con taller en funcionamiento, de 610 metros cuadrados que se puede destinar a distintos usos. Gran espacio amplio y zona de oficina. Se puede vender conjuntamente con el solar que está situado justo detrás, contiguo, que se puede ver en las últimas dos fotos, el cual ocupa 750 metros cuadrados más, por un total de 578.000€. Situado en el polígono industrial de Hospitalet de l´Infant. Su núcleo de población está situado en la costa, donde se puede disfrutar de sus largas playas y clima cálido. Se encuentra también en un punto donde diferentes vías se cruzan para comodidad de sus habitantes a la hora de viajar y visitar las poblaciones lindantes. Pueblo perfecto para pasar las vacaciones en familia y con tranquilidad."
    },
    { 
        id: "CZ508",
        titulo: "Local en el centro de Miami Platja", 
        precio: "130.000€", 
        poblacion: "Miami Platja", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/xTvVK7tC/cz508-01.jpg",
            "https://i.postimg.cc/pXfMD7qy/cz508-02.jpg",
            "https://i.postimg.cc/8PRgh3tj/cz508-03.jpg",
            "https://i.postimg.cc/bNxfQM3G/cz508-04.jpg",
            "https://i.postimg.cc/bwqcLTBw/cz508-05.jpg",
            "https://i.postimg.cc/K8mSQNHj/cz508-06.jpg",
            "https://i.postimg.cc/jSR0vXF5/cz508-07.jpg",
            "https://i.postimg.cc/VkzQ4RVW/cz508-08.jpg",
            "https://i.postimg.cc/dVJPnBxn/cz508-09.jpg",
            "https://i.postimg.cc/3x359BcL/cz508-10.jpg",
            "https://i.postimg.cc/YCtK83sn/cz508-11.jpg",
            "https://i.postimg.cc/52fdp3RK/cz508-12.jpg",
            "https://i.postimg.cc/0yZg4wTf/cz508-13.jpg",
            "https://i.postimg.cc/L8mKvTbW/cz508-14.jpg",
            "https://i.postimg.cc/NjbhnH3x/cz508-15.jpg"
        ],
        metros: 95, 
        baños: 1, 
        descripcion: "Local de 95 metros cuadrados en una de las calles más comerciales de Miami Platja, contigua a la avenida principal del pueblo, lo cual deriva en una gran afluencia de gente."
    },
    { 
        id: "CZ511",
        titulo: "Local en la Avenida Valencia de Miami Platja", 
        precio: "69.000€", 
        poblacion: "Miami Platja", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/9fN6mjFd/cz511-01.jpg",
            "https://i.postimg.cc/QMn28rxp/cz511-02.jpg",
            "https://i.postimg.cc/3wbs8HJm/cz511-03.jpg",
            "https://i.postimg.cc/nLwyFtcq/cz511-04.jpg",
            "https://i.postimg.cc/hG3kDqP1/cz511-05.jpg",
            "https://i.postimg.cc/Ls0c9M6N/cz511-06.jpg",
            "https://i.postimg.cc/wBbCqdTF/cz511-07.jpg",
            "https://i.postimg.cc/hG3kDqPC/cz511-08.jpg",
            "https://i.postimg.cc/q7ZPJdMb/cz511-09.jpg",
            "https://i.postimg.cc/rpYBVLFP/cz511-10.jpg",
            "https://i.postimg.cc/g0BCzPkB/cz511-11.jpg",
            "https://i.postimg.cc/wBbCqdTP/cz511-12.jpg",
            "https://i.postimg.cc/vmSJYdHk/cz511-13.jpg",
            "https://i.postimg.cc/fbgGzhT1/cz511-14.jpg",
            "https://i.postimg.cc/5tkh4MNh/cz511-15.jpg",
            "https://i.postimg.cc/rpYBVLFv/cz511-16.jpg",
            "https://i.postimg.cc/MTMhXrvd/cz511-17.jpg",
            "https://i.postimg.cc/XJGTXDp2/cz511-18.jpg",
            "https://i.postimg.cc/W3FQtfhW/cz511-19.jpg",
            "https://i.postimg.cc/4d7rnFmD/cz511-20.jpg",
            "https://i.postimg.cc/LXYrh0JK/cz511-21.jpg",
            "https://i.postimg.cc/MTMhXrnJ/cz511-22.jpg",
            "https://i.postimg.cc/ydgwWrDs/cz511-23.jpg"
        ],
        metros: 66, 
        baños: 2, 
        descripcion: "Local comercial, el cual fue anteriormente usado para emplazar un Bar, situado en la Avenida Valencia haciendo esquina con la Avenida Barcelona, la más transitada de todo Miami Platja. Aforo interior de 45 personas y recinto exterior con capacidad para montar una terraza. Establecimiento con 2 baños, barra de bar instalada, aire acondicionado y ventiladores de techo. Aprovecha la oportunidad de hacerte con el lugar donde puede ubicarse tu negocio."
    },
    { 
        id: "CZ513",
        titulo: "Local de dos plantas en Tarragona", 
        precio: "245.000€", 
        poblacion: "Tarragona", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/GmLVvpB0/cz513-01.jpg",
            "https://i.postimg.cc/HkYRbLrf/cz513-02.jpg",
            "https://i.postimg.cc/L89wjsqK/cz513-03.jpg",
            "https://i.postimg.cc/BnSk2vjr/cz513-04.jpg",
            "https://i.postimg.cc/Mp9458BC/cz513-05.jpg",
            "https://i.postimg.cc/y8L5jz9z/cz513-06.jpg",
            "https://i.postimg.cc/52sGgMvW/cz513-07.jpg",
            "https://i.postimg.cc/W15K8PrR/cz513-08.jpg",
            "https://i.postimg.cc/t4BfkHP4/cz513-09.jpg",
            "https://i.postimg.cc/FHTqpQcK/cz513-10.jpg",
            "https://i.postimg.cc/13vTBZ6X/cz513-11.jpg",
            "https://i.postimg.cc/mgmqjGMD/cz513-12.jpg",
            "https://i.postimg.cc/T3tS0Xmp/cz513-13.jpg",
            "https://i.postimg.cc/fbkPggjM/cz513-14.jpg"
        ],
        metros: 418, 
        baños: 4, 
        descripcion: "Local comercial de dos plantas con una gran superficie de 155 metros cuadrados y muy llamativo debido a sus anchos escaparates con gran visibilidad desde el exterior. Cuenta con dos amplias estancias diáfanas, con un trastero en cada planta y con cuatro baños, dos de ellos con ducha. En buen estado, preparado para iniciar tu negocio tras unos pocos días de preparación, con todas las instalaciones en regla, con aire acondicionado completamente funcional,  Desplazamiento entre plantas tanto mediante escaleras como mediante ascensor, contando también ambas plantas con entrada propia, lo cual podría ser útil para crear dos locales totalmente independientes. Anteriormente la actividad llevada a cabo en el local fue la de un centro de belleza, pero las posibilidades que ofrecen las características particulares de este local son infinitas. El inmueble se encuentra en una ubicación muy céntrica de Tarragona, cerca de la Plaza Imperial Tárraco, en una zona con gran afluencia de transeúntes."
    },
    { 
        id: "CZ514",
        titulo: "Local en el centro de Miami Platja", 
        precio: "90.000€", 
        poblacion: "Miami Platja", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/xTRFjS66/cz514-01.jpg",
            "https://i.postimg.cc/6ppby1Pn/cz514-02.jpg",
            "https://i.postimg.cc/1337fYdD/cz514-03.jpg",
            "https://i.postimg.cc/gkDBcPgs/cz514-04.jpg",
            "https://i.postimg.cc/x11pcFZP/cz514-05.jpg",
            "https://i.postimg.cc/kggYBhHf/cz514-06.jpg",
            "https://i.postimg.cc/6ppby1PF/cz514-07.jpg",
            "https://i.postimg.cc/sggHv0Lq/cz514-08.jpg",
            "https://i.postimg.cc/fRRqJgFh/cz514-09.jpg",
            "https://i.postimg.cc/T33NpHsz/cz514-10.jpg",
            "https://i.postimg.cc/7Zts7nvc/cz514-11.jpg",
            "https://i.postimg.cc/t4vSPN08/cz514-12.jpg",
            "https://i.postimg.cc/Sx1T8fFp/cz514-13.jpg",
            "https://i.postimg.cc/RZpsfL5m/cz514-14.jpg",
            "https://i.postimg.cc/0yXWm0Ry/cz514-15.jpg",
            "https://i.postimg.cc/mgpXMyfr/cz514-16.jpg"
        ],
        metros:117, 
        descripcion: "Finques TIVI3 presenta esta oportunidad perfecta para tu negocio, un local de 117 metros cuadrados situado en la avenida principal de la población de Miami Playa. Como se puede apreciar, es un amplio local con muchas posibilidades, y con algunas instalaciones que perfectamente pueden ser aprovechadas, con una decoración rústica y pintoresca, que bien se puede mantener o se puede renovar. Existe la posibilidad de comprar conjuntamente un apartamento de 85 metros cuadrados que se encuentra encima del local por 130.000€ más, para poder compaginar vida y trabajo cómodamente. El inmueble cuenta con una estancia principal muy grande, la cual goza de aire acondicionado, y con otras tres que bien pueden ser destinadas a actividades tales como cocina, almacén, baños, o lo que sea conveniente."
    },
    { 
        id: "CZA018",
        titulo: "Plaza doble de parking en Tivissa", 
        precio: "60€/mes", 
        poblacion: "Tivissa", 
        tipo: "Parking", 
        transaccion: "Alquiler", 
        fotos: [
            "https://i.postimg.cc/MT2YbssJ/cza018-01.jpg",
            "https://i.postimg.cc/d1P9mWWK/cza018-02.jpg",
            "https://i.postimg.cc/HxDt4SSG/cza018-03.jpg",
            "https://i.postimg.cc/xCDPyssQ/cza018-04.jpg",
            "https://i.postimg.cc/V6QFB771/cza018-05.jpg",
            "https://i.postimg.cc/G2wjJMMd/cza018-06.jpg"
        ],
        metros: 17, 
        descripcion: "Esta plaza doble de parking (de 11 y 6 metros cuadrados) se encuentra ubicado en una tranquila zona en una calle céntrica del municipio de Tivissa, al lado del restaurante Missamaroi y cerca del parque de bomberos. Tiene fácil acceso, es una calle poco transitada, y está bien conectada hacia ambas direcciones."
    },
    { 
        id: "CZA033",
        titulo: "Local en el puerto de Hospitalet de l'Infant", 
        precio: "650€/mes", 
        poblacion: "Hospitalet de l'Infant", 
        tipo: "Local", 
        transaccion: "Alquiler", 
        fotos: [
            "https://i.postimg.cc/05CCD07k/cza033-01.jpg",
            "https://i.postimg.cc/PfMMYQ1f/cza033-02.jpg",
            "https://i.postimg.cc/sfJJ745D/cza033-03.jpg",
            "https://i.postimg.cc/9XBBZYyQ/cza033-04.jpg",
            "https://i.postimg.cc/DfccLP1Z/cza033-05.jpg",
            "https://i.postimg.cc/kMyyKvWG/cza033-06.jpg",
            "https://i.postimg.cc/rFFNJR9L/cza033-07.jpg",
            "https://i.postimg.cc/c44BmtcS/cza033-08.jpg",
            "https://i.postimg.cc/rFFNJR9F/cza033-09.jpg",
            "https://i.postimg.cc/DyyPg4cW/cza033-10.jpg"
        ],
        metros: 60, 
        baños: 1, 
        descripcion: "Existe la posibilidad de adquirir este local en formato de alquiler con opción a compra, ejecutable en un máximo de 3 años y/o dando una entrada inicial, consúltanos para que te informemos más a fondo si ese es el caso. No dejes escapar la posibilidad de ubicar tu negocio en la zona más concurrida de esta población y alrededores, haciéndote con este local situado en el puerto de Hospitalet de l'Infant.  Se trata de un local estándar de 60 metros cuadrados que ha sido en los últimos meses completamente reformado, con parqué, instalación eléctrica a la última, aire acondicionado, etc. El local destaca por su amplia cristalera que ocupa toda la fachada, ofreciendo una gran visibilidad a cualquier transeúnte que transite por el puerto. Por dentro está dividido en una gran estancia principal, en un baño particular, y en una estancia separada la cual puede ser destinada a despacho privado entre otras posibilidades."
    },
    { 
        id: "CZW003",
        titulo: "Chalet adosado en Miami Platja", 
        precio: "270.000€", 
        poblacion: "Miami Platja", 
        tipo: "Casa", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/RZ214sxJ/czw003-01.jpg",
            "https://i.postimg.cc/W1xmTWcZ/czw003-02.jpg",
            "https://i.postimg.cc/htN8cyRz/czw003-03.jpg",
            "https://i.postimg.cc/P50bT3n8/czw003-04.jpg",
            "https://i.postimg.cc/bw40pCfQ/czw003-05.jpg",
            "https://i.postimg.cc/JzS3M6CN/czw003-06.jpg",
            "https://i.postimg.cc/Z5XP47zH/czw003-07.jpg",
            "https://i.postimg.cc/t48dpSGD/czw003-08.jpg",
            "https://i.postimg.cc/2SgdrcN2/czw003-09.jpg",
            "https://i.postimg.cc/pL3QRGMs/czw003-10.jpg",
            "https://i.postimg.cc/vm9rBrG5/czw003-11.jpg",
            "https://i.postimg.cc/Mpg0qPJP/czw003-12.jpg",
            "https://i.postimg.cc/g21ymSbM/czw003-13.jpg",
            "https://i.postimg.cc/5tvB0Bfw/czw003-14.jpg",
            "https://i.postimg.cc/nL74z4nG/czw003-15.jpg",
            "https://i.postimg.cc/FKcyRyhx/czw003-16.jpg",
            "https://i.postimg.cc/jjNH5HRc/czw003-17.jpg",
            "https://i.postimg.cc/TPmVwVTC/czw003-18.jpg",
            "https://i.postimg.cc/SK86s6mg/czw003-19.jpg",
            "https://i.postimg.cc/nL74z4nS/czw003-20.jpg"
        ],
        metros: 140, 
        habitaciones: 3, 
        baños: 3, 
        descripcion: "Preciosa casa pareada y esquinera, muy soleada, situada a escasos metros del centro y de la playa, con garaje y posibilidad de aparcar otro coche dentro del recinto de la casa. Tres grandes terrazas permiten disfrutar del maravilloso clima de la costa dorada. La terraza tiene salida directa una piscina con bonitas escaleras de obra, lugar ideal para descansar y tomar el sol, a la vez que disfrutar al aire libre en familia. En la planta baja de la casa, después del porche de entrada está el comedor con mucha luz, dando acceso a la parte de piscina y jardín. En la misma planta está una gran cocina totalmente independiente y equipada con nevera, placa de inducción, horno, microondas y lavadora. La ventana de la cocina tiene vista a la piscina, barbacoa y jardín. En esta misma planta tenemos una habitación doble con baño con vistas a la piscina. La escalera de mármol da acceso a la planta superior donde hay dos habitaciones dobles con armario empotrado, la primera habitación de matrimonio con acceso a una terraza orientada al mar y un segundo dormitorio doble con un cuarto de baño completo con vistas a la piscina y jardín. En la parte baja podrán disfrutar de sus baños en la piscina, relax en las tumbonas, así como disfrutar de las barbacoas que podrán organizar con familiares y amigos. La casa dispone de un sistema de aire acondicionado que les ofrece la posibilidad de frio en verano y calor en invierno. La casa está en perfecto estado, ha sido de uso exclusivo de la familia sin haberse explotado vacacionalmente."
    },
    { 
        id: "CZW006",
        titulo: "Tres casas en una en Miami Platja", 
        precio: "480.000€", 
        poblacion: "Miami Platja", 
        tipo: "Casa", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/s2X2HyNZ/czw006-01.jpg",
            "https://i.postimg.cc/cJHJkZbw/czw006-02.jpg",
            "https://i.postimg.cc/wBvB4HGJ/czw006-03.jpg",
            "https://i.postimg.cc/ZqRqsZM6/czw006-04.jpg",
            "https://i.postimg.cc/xdCdpY45/czw006-05.jpg",
            "https://i.postimg.cc/KYzYpFHs/czw006-06.jpg",
            "https://i.postimg.cc/3wRwf7cn/czw006-07.jpg",
            "https://i.postimg.cc/g0J0tdTt/czw006-08.jpg",
            "https://i.postimg.cc/QMydRP2b/czw006-09.jpg",
            "https://i.postimg.cc/mr5g0qvj/czw006-10.jpg",
            "https://i.postimg.cc/XvzYThRx/czw006-11.jpg",
            "https://i.postimg.cc/fbrR6FG8/czw006-12.jpg",
            "https://i.postimg.cc/N0zjWV3z/czw006-13.jpg",
            "https://i.postimg.cc/VNVk3Tx2/czw006-14.jpg",
            "https://i.postimg.cc/0NByLFgg/czw006-15.jpg",
            "https://i.postimg.cc/ZqM512kt/czw006-16.jpg",
            "https://i.postimg.cc/d0xVzpMs/czw006-17.jpg"
        ],
        metros: 300, 
        parcela: 615,
        habitaciones: 3,
        baños: 3, 
        garaje: "Sí",
        descripcion: "Preciosa casa que cuenta como 3 casas distintas, con 3 cédulas de habitabilidad separadas y 3 certificados energéticos con sus 3 contadores. Todo amueblado, el primer piso cuenta con 2 aires acondicionados independientes, capaces de dar tanto frío como calor. El terreno cuenta con 615 metros cuadrados, e incluye tanto cochera como una zona de barbacoa exterior. En total tenemos 26 metros de fachada."
    },
    { 
        id: "HFL301",
        titulo: "Local céntrico en Miami Platja", 
        precio: "99.000€", 
        poblacion: "Miami Platja", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/43mJbPYb/hfl301-01.jpg",
            "https://i.postimg.cc/Dz82d6Sq/hfl301-02.jpg",
            "https://i.postimg.cc/ZqCTFHWx/hfl301-03.jpg",
            "https://i.postimg.cc/8Cj1B47d/hfl301-04.jpg",
            "https://i.postimg.cc/25VzFG1H/hfl301-05.jpg",
            "https://i.postimg.cc/tgYXtksS/hfl301-06.jpg",
            "https://i.postimg.cc/N05g7DKP/hfl301-08.jpg"
        ],
        metros: 90, 
        baños: 1, 
        descripcion: "Local comercial de 90 metros cuadrados con acceso directo desde la calle California en Miami Platja. Se trata de un local diáfano, con un baño y cuarto trastero/almacén. Cuenta con rejas y cerramientos de aluminio blanco. Es perfecto para cualquier negocio u oficina. Las viviendas del entorno corresponden a edificios plurifamiliares, teniendo el barrio carácter urbano consolidado."
    },
    { 
        id: "PKGA017",
        titulo: "Plaza de parking en Sant Joan Despí", 
        precio: "80€/mes", 
        poblacion: "Sant Joan Despí", 
        tipo: "Parking", 
        transaccion: "Alquiler", 
        fotos: [
            "https://i.postimg.cc/xTfV357R/pkga017-01.png"
        ],
        metros: 12, 
        descripcion: "Cómoda plaza de parking de un garaje cubierto ubicado en Sant Joan Despí, concretamente en la calle Josep Trueta."
    },
    { 
        id: "PKGA024",
        titulo: "Plaza de parking en Sant Joan Despí", 
        precio: "90€/mes", 
        poblacion: "Sant Joan Despí", 
        tipo: "Parking", 
        transaccion: "Alquiler", 
        fotos: [
            "https://i.postimg.cc/fLc1xSfj/pkga024-01.jpg",
            "https://i.postimg.cc/vBrCWxtz/pkga024-02.jpg",
            "https://i.postimg.cc/JnNSbH55/pkga024-03.jpg",
            "https://i.postimg.cc/j5HBzn4v/pkga024-04.jpg",
            "https://i.postimg.cc/ZR8XrvxQ/pkga024-05.jpg",
            "https://i.postimg.cc/QtQvpKJP/pkga024-06.jpg",
            "https://i.postimg.cc/C1G9jns9/pkga024-07.png",
            "https://i.postimg.cc/vBrCWxvR/pkga024-08.png"
        ],
        metros: 12, 
        descripcion: "Cómoda plaza de parking de un garaje cubierto ubicado en Sant Joan Despí, concretamente en la calle Sant Martí de l´Erm."
    },
    { 
        id: "PKGA025",
        titulo: "Plaza de parking en Sant Joan Despí", 
        precio: "100€/mes", 
        poblacion: "Sant Joan Despí", 
        tipo: "Parking", 
        transaccion: "Alquiler", 
        fotos: [
            "https://i.postimg.cc/gj45795H/pkga025-01.png",
            "https://i.postimg.cc/RhG8Yr8T/pkga025-02.png"
        ],
        metros: 12, 
        descripcion: "Cómoda plaza de parking de un garaje cubierto ubicado en Sant Joan Despí, concretamente en la calle Sant Martí de l´Erm."
    },
    { 
        id: "TRA017",
        titulo: "Trastero en Sant Joan Despí", 
        precio: "100€/mes", 
        poblacion: "Sant Joan Despí", 
        tipo: "Trastero", 
        transaccion: "Alquiler", 
        fotos: [
            "https://i.postimg.cc/KvvCMzkk/tra017-01.jpg",
            "https://i.postimg.cc/J44SknDy/tra017-02.jpg",
            "https://i.postimg.cc/yYY2Zdg3/tra017-03.jpg",
            "https://i.postimg.cc/pXX3FThm/tra017-04.jpg"
        ],
        metros: 10, 
        descripcion: "Trastero de 10 metros cuadrados situado junto a más trasteros, con entrada a pie de calle, protegido por una puerta metálica."
    },
    { 
        id: "V316",
        titulo: "Plaza de parking en Sant Joan Despí", 
        precio: "17.500€", 
        poblacion: "Sant Joan Despí", 
        tipo: "Parking", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/kg2ZTpyK/v316-01.jpg",
            "https://i.postimg.cc/VkJTKVFt/v316-02.jpg",
            "https://i.postimg.cc/sgM8TNJp/v316-03.jpg",
            "https://i.postimg.cc/dVhX5x9G/v316-04.jpg",
            "https://i.postimg.cc/4xYMWS15/v316-05.jpg",
            "https://i.postimg.cc/cLvjFbch/v316-06.jpg",
            "https://i.postimg.cc/JzSFv5TZ/v316-07.jpg"
        ],
        metros: 13, 
        descripcion: "Cómoda plaza de parking de un garaje cubierto ubicado en Sant Joan Despí, concretamente en la calle Sant Martí de l´Erm, con espacio para un coche grande y una moto conjuntamente."
    },
    { 
        id: "V321",
        titulo: "Solar residencial en La Seu d'Urgell", 
        precio: "315.000€", 
        poblacion: "La Seu d'Urgell", 
        tipo: "Terreno", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/sX40Bd3P/v321-01.png"
        ],
        metros: 500, 
        descripcion: "Hazte con un solar urbanizable de 500 metros cuadrados en la calle Setúria de La Seu d´Urgell."
    },
    { 
        id: "V324",
        titulo: "Piso ideal para jóvenes en Cornellà", 
        precio: "86.000€", 
        poblacion: "Cornellà de Llobregat", 
        tipo: "Piso", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/vTPqzrgc/v324-01.jpg",
            "https://i.postimg.cc/qqmbLshN/v324-02.jpg",
            "https://i.postimg.cc/pr0GZfhj/v324-03.jpg",
            "https://i.postimg.cc/j28gXHw7/v324-04.jpg",
            "https://i.postimg.cc/hvCyrLzT/v324-05.jpg",
            "https://i.postimg.cc/sxn6cYQQ/v324-06.jpg",
            "https://i.postimg.cc/FzPWZydj/v324-07.jpg",
            "https://i.postimg.cc/Y0Xn36GN/v324-08.jpg",
            "https://i.postimg.cc/rshnJ10N/v324-09.jpg",
            "https://i.postimg.cc/7hBsV3G9/v324-10.jpg",
            "https://i.postimg.cc/fyH2KctB/v324-11.jpg",
            "https://i.postimg.cc/8cyKHRJZ/v324-12.jpg",
            "https://i.postimg.cc/yxfQPmgf/v324-13.jpg",
            "https://i.postimg.cc/Kj9qNPks/v324-14.jpg",
            "https://i.postimg.cc/Y0Xn36GD/v324-15.jpg"
        ],
        metros: 32, 
        baños: 1, 
        descripcion: "Piso a pie de calle ideal para parejas en la población de Cornellà de Llobregat. Pese a tratarse de un estudio y estar reformado como tal, se transmite como local, por lo que carece de cédula de habitabilidad. 32 metros de vivienda completamente adaptados para vivir, con todas las comodidades necesarias, y con un diseño de interior único como se puede contemplar. Un salón con cocina americana totalmente equipada, la cual cuenta con campana extractora; una habitación con una decente luminosidad; un baño con plato de ducha. Inmueble actualmente con inquilinos fijos, los cuales aportan una rentabilidad mensualmente. Oportunidad perfecta para inversores que quieran comprar el inmueble y recibir rentas de él."
    },
    { 
        id: "V334",
        titulo: "Local esquinero en Sant Joan Despí", 
        precio: "270.000€", 
        poblacion: "Sant Joan Despí", 
        tipo: "Local", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/W1qWGJ23/v334-01.jpg",
            "https://i.postimg.cc/xT4pNPSm/v334-02.jpg",
            "https://i.postimg.cc/13VCGN98/v334-03.jpg",
            "https://i.postimg.cc/2SLcQBz5/v334-04.jpg",
            "https://i.postimg.cc/x1Nxvb0z/v334-05.jpg",
            "https://i.postimg.cc/4xHL6hJp/v334-06.jpg",
            "https://i.postimg.cc/qv6bsCkc/v334-07.jpg",
            "https://i.postimg.cc/SxYT6zyG/v334-08.jpg",
            "https://i.postimg.cc/9Qw8dqWx/v334-09.jpg",
            "https://i.postimg.cc/43C8BNdb/v334-10.jpg",
            "https://i.postimg.cc/q7fmjMRx/v334-11.jpg",
            "https://i.postimg.cc/nL8d0czk/v334-12.jpg",
            "https://i.postimg.cc/FKtPDsRW/v334-13.jpg",
            "https://i.postimg.cc/vmRP3HBS/v334-14.jpg",
            "https://i.postimg.cc/0Ngtc2Q4/v334-15.jpg",
            "https://i.postimg.cc/TP8kCYwZ/v334-16.jpg",
            "https://i.postimg.cc/wBKW0TMd/v334-17.jpg",
            "https://i.postimg.cc/k5rjfXGm/v334-18.jpg",
            "https://i.postimg.cc/FKtPDszv/v334-19.jpg",
            "https://i.postimg.cc/k5rjfXG7/v334-20.jpg"
        ],
        metros: 150, 
        baños: 1, 
        descripcion: "Local situado en la mejor posición del barrio, una esquina con mucha afluencia de gente. Se trata de un local de 150 metros cuadrados distribuidos en 2 plantas, con barra y cocina en la inferior. Persiana motorizada, cerramientos de aluminio, máquinas de aire acondicionado, etc."
    },
    { 
        id: "V338",
        titulo: "Piso en Sant Joan Despí", 
        precio: "549.000€", 
        poblacion: "Sant Joan Despí", 
        tipo: "Piso", 
        transaccion: "Compra", 
        fotos: [
            "https://i.postimg.cc/hGb0sLNT/v338-01.jpg",
            "https://i.postimg.cc/rpC9j17r/v338-02.jpg",
            "https://i.postimg.cc/jjQhcHBy/v338-03.jpg",
            "https://i.postimg.cc/GpJjKF68/v338-04.jpg",
            "https://i.postimg.cc/FKgxpywT/v338-05.jpg",
            "https://i.postimg.cc/PxXQRLkZ/v338-06.jpg",
            "https://i.postimg.cc/RFSLD3zw/v338-07.jpg",
            "https://i.postimg.cc/hjD15Jq9/v338-08.jpg",
            "https://i.postimg.cc/rmVNPdLN/v338-09.jpg",
            "https://i.postimg.cc/xCf34kSR/v338-10.jpg",
            "https://i.postimg.cc/63Wfm7NY/v338-11.jpg",
            "https://i.postimg.cc/FRrVBfQP/v338-12.jpg",
            "https://i.postimg.cc/KzGDHKy6/v338-13.jpg",
            "https://i.postimg.cc/Jnr52yLV/v338-14.jpg",
            "https://i.postimg.cc/cHxBbKSN/v338-15.jpg",
            "https://i.postimg.cc/LXx3KHHw/v338-16.jpg",
            "https://i.postimg.cc/mDmyfbb0/v338-17.jpg",
            "https://i.postimg.cc/W35wL2NR/v338-18.jpg",
            "https://i.postimg.cc/d15jPqsw/v338-19.jpg",
            "https://i.postimg.cc/vB0tFQYD/v338-20.jpg"
        ],
        metros: 100, 
        habitaciones: 4,
        baños: 2, 
        descripcion: "Finques TIVI3 te trae este acogedor piso en la zona de la TV3 de Sant Joan Despí. Cuenta con un salón-comedor bastante amplio con su propia terraza que da a un exterior con vistas al parque central de la manzana. 4 habitaciones, 2 de ellas con camas y armarios (1 de ellos empotrado), todas muy bien iluminadas gracias a sus ventanales. Una cocina completamente equipada la cual da acceso a un lavadero. 2 baños completos, uno con bañera y el otro con plato de ducha. Incluido en el precio viene una plaza propia en el parking del edificio."
    }
];